import { Country } from '@/shared/type';

const COUNTRIES: Country[] = [
  {
    title: '가나',
    description: 'Ghana (Africa)',
    imageUrl: 'https://flagcdn.com/gh.svg',
    isoCode: 'GH',
  },
  {
    title: '가봉',
    description: 'Gabon (Africa)',
    imageUrl: 'https://flagcdn.com/ga.svg',
    isoCode: 'GA',
  },
  {
    title: '가이아나',
    description: 'Guyana (South America)',
    imageUrl: 'https://flagcdn.com/gy.svg',
    isoCode: 'GY',
  },
  {
    title: '감비아',
    description: 'Gambia (Africa)',
    imageUrl: 'https://flagcdn.com/gm.svg',
    isoCode: 'GM',
  },
  {
    title: '건지',
    description: 'Guernsey (Europe)',
    imageUrl: 'https://flagcdn.com/gg.svg',
    isoCode: 'GG',
  },
  {
    title: '과들루프',
    description: 'Guadeloupe (North America)',
    imageUrl: 'https://flagcdn.com/gp.svg',
    isoCode: 'GP',
  },
  {
    title: '과테말라',
    description: 'Guatemala (North America)',
    imageUrl: 'https://flagcdn.com/gt.svg',
    isoCode: 'GT',
  },
  {
    title: '괌',
    description: 'Guam (Asia)',
    imageUrl: 'https://flagcdn.com/gu.svg',
    isoCode: 'GU',
  },
  {
    title: '그레나다',
    description: 'Grenada (North America)',
    imageUrl: 'https://flagcdn.com/gd.svg',
    isoCode: 'GD',
  },
  {
    title: '그리스',
    description: 'Greece (Europe)',
    imageUrl: 'https://flagcdn.com/gr.svg',
    isoCode: 'GR',
  },
  {
    title: '그린란드',
    description: 'Greenland (North America)',
    imageUrl: 'https://flagcdn.com/gl.svg',
    isoCode: 'GL',
  },
  {
    title: '기니',
    description: 'Guinea (Africa)',
    imageUrl: 'https://flagcdn.com/gn.svg',
    isoCode: 'GN',
  },
  {
    title: '기니비사우',
    description: 'Guinea-Bissau (Africa)',
    imageUrl: 'https://flagcdn.com/gw.svg',
    isoCode: 'GW',
  },
  {
    title: '나미비아',
    description: 'Namibia (Africa)',
    imageUrl: 'https://flagcdn.com/na.svg',
    isoCode: 'NA',
  },
  {
    title: '나우루',
    description: 'Nauru (Asia)',
    imageUrl: 'https://flagcdn.com/nr.svg',
    isoCode: 'NR',
  },
  {
    title: '나이지리아',
    description: 'Nigeria (Africa)',
    imageUrl: 'https://flagcdn.com/ng.svg',
    isoCode: 'NG',
  },
  {
    title: '남수단',
    description: 'South Sudan (Africa)',
    imageUrl: 'https://flagcdn.com/ss.svg',
    isoCode: 'SS',
  },
  {
    title: '남아프리카공화국',
    description: 'South Africa (Africa)',
    imageUrl: 'https://flagcdn.com/za.svg',
    isoCode: 'ZA',
  },
  {
    title: '네덜란드',
    description: 'Netherlands (Europe)',
    imageUrl: 'https://flagcdn.com/nl.svg',
    isoCode: 'NL',
  },
  {
    title: '노르웨이',
    description: 'Norway (Europe)',
    imageUrl: 'https://flagcdn.com/no.svg',
    isoCode: 'NO',
  },
  {
    title: '뉴칼레도니아',
    description: 'New Caledonia (Asia)',
    imageUrl: 'https://flagcdn.com/nc.svg',
    isoCode: 'NC',
  },
  {
    title: '뉴질랜드',
    description: 'New Zealand (Asia)',
    imageUrl: 'https://flagcdn.com/nz.svg',
    isoCode: 'NZ',
  },
  {
    title: '니제르',
    description: 'Niger (Africa)',
    imageUrl: 'https://flagcdn.com/ne.svg',
    isoCode: 'NE',
  },
  {
    title: '니카라과',
    description: 'Nicaragua (North America)',
    imageUrl: 'https://flagcdn.com/ni.svg',
    isoCode: 'NI',
  },
  {
    title: '대만',
    description: 'Taiwan (Asia)',
    imageUrl: 'https://flagcdn.com/tw.svg',
    isoCode: 'TW',
  },
  {
    title: '대한민국',
    description: 'Korea (Asia)',
    imageUrl: 'https://flagcdn.com/kr.svg',
    isoCode: 'KR',
  },
  {
    title: '덴마크',
    description: 'Denmark (Europe)',
    imageUrl: 'https://flagcdn.com/dk.svg',
    isoCode: 'DK',
  },
  {
    title: '도미니카공화국',
    description: 'Dominican Republic (North America)',
    imageUrl: 'https://flagcdn.com/do.svg',
    isoCode: 'DO',
  },
  {
    title: '도미니카연방',
    description: 'Dominica (North America)',
    imageUrl: 'https://flagcdn.com/dm.svg',
    isoCode: 'DM',
  },
  {
    title: '라오스',
    description: 'Laos (Asia)',
    imageUrl: 'https://flagcdn.com/la.svg',
    isoCode: 'LA',
  },
  {
    title: '라이베리아',
    description: 'Liberia (Africa)',
    imageUrl: 'https://flagcdn.com/lr.svg',
    isoCode: 'LR',
  },
  {
    title: '라트비아',
    description: 'Latvia (Europe)',
    imageUrl: 'https://flagcdn.com/lv.svg',
    isoCode: 'LV',
  },
  {
    title: '러시아',
    description: 'Russia (Europe)',
    imageUrl: 'https://flagcdn.com/ru.svg',
    isoCode: 'RU',
  },
  {
    title: '레바논',
    description: 'Lebanon (Middle East)',
    imageUrl: 'https://flagcdn.com/lb.svg',
    isoCode: 'LB',
  },
  {
    title: '레소토',
    description: 'Lesotho (Africa)',
    imageUrl: 'https://flagcdn.com/ls.svg',
    isoCode: 'LS',
  },
  {
    title: '루마니아',
    description: 'Romania (Europe)',
    imageUrl: 'https://flagcdn.com/ro.svg',
    isoCode: 'RO',
  },
  {
    title: '룩셈부르크',
    description: 'Luxembourg (Europe)',
    imageUrl: 'https://flagcdn.com/lu.svg',
    isoCode: 'LU',
  },
  {
    title: '르완다',
    description: 'Rwanda (Africa)',
    imageUrl: 'https://flagcdn.com/rw.svg',
    isoCode: 'RW',
  },
  {
    title: '리비아',
    description: 'Libya (Africa)',
    imageUrl: 'https://flagcdn.com/ly.svg',
    isoCode: 'LY',
  },
  {
    title: '리투아니아',
    description: 'Lithuania (Europe)',
    imageUrl: 'https://flagcdn.com/lt.svg',
    isoCode: 'LT',
  },
  {
    title: '리히텐슈타인',
    description: 'Liechtenstein (Europe)',
    imageUrl: 'https://flagcdn.com/li.svg',
    isoCode: 'LI',
  },
  {
    title: '마다가스카르',
    description: 'Madagascar (Africa)',
    imageUrl: 'https://flagcdn.com/mg.svg',
    isoCode: 'MG',
  },
  {
    title: '마르티니크',
    description: 'Martinique (North America)',
    imageUrl: 'https://flagcdn.com/mq.svg',
    isoCode: 'MQ',
  },
  {
    title: '마셜제도',
    description: 'Marshall Islands (Asia)',
    imageUrl: 'https://flagcdn.com/mh.svg',
    isoCode: 'MH',
  },
  {
    title: '마요트',
    description: 'Mayotte (Africa)',
    imageUrl: 'https://flagcdn.com/yt.svg',
    isoCode: 'YT',
  },
  {
    title: '마이크로네시아연방',
    description: 'Federated States of Micronesia (Asia)',
    imageUrl: 'https://flagcdn.com/fm.svg',
    isoCode: 'FM',
  },
  {
    title: '마카오',
    description: 'Macao (Asia)',
    imageUrl: 'https://flagcdn.com/mo.svg',
    isoCode: 'MO',
  },
  {
    title: '말라위',
    description: 'Malawi (Africa)',
    imageUrl: 'https://flagcdn.com/mw.svg',
    isoCode: 'MW',
  },
  {
    title: '말라가',
    description: 'Malaga (Africa)',
    imageUrl: 'https://flagcdn.com/ml.svg',
    isoCode: 'ML',
  },
  {
    title: '말레이시아',
    description: 'Malaysia (Asia)',
    imageUrl: 'https://flagcdn.com/my.svg',
    isoCode: 'MY',
  },
  {
    title: '모나코',
    description: 'Monaco (Europe)',
    imageUrl: 'https://flagcdn.com/mc.svg',
    isoCode: 'MC',
  },
  {
    title: '모리셔스',
    description: 'Mauritius (Africa)',
    imageUrl: 'https://flagcdn.com/mu.svg',
    isoCode: 'MU',
  },
  {
    title: '모로코',
    description: 'Morocco (Middle East)',
    imageUrl: 'https://flagcdn.com/ma.svg',
    isoCode: 'MA',
  },
  {
    title: '모리타니아',
    description: 'Mauritania (Africa)',
    imageUrl: 'https://flagcdn.com/mr.svg',
    isoCode: 'MR',
  },
  {
    title: '몰도바',
    description: 'Moldova (Europe)',
    imageUrl: 'https://flagcdn.com/md.svg',
    isoCode: 'MD',
  },
  {
    title: '몰디브',
    description: 'Maldives (Asia)',
    imageUrl: 'https://flagcdn.com/mv.svg',
    isoCode: 'MV',
  },
  {
    title: '몬테네그로',
    description: 'Montenegro (Europe)',
    imageUrl: 'https://flagcdn.com/me.svg',
    isoCode: 'ME',
  },
  {
    title: '몬트세랫',
    description: 'Montserrat (North America)',
    imageUrl: 'https://flagcdn.com/ms.svg',
    isoCode: 'MS',
  },
  {
    title: '몽골',
    description: 'Mongolia (Asia)',
    imageUrl: 'https://flagcdn.com/mn.svg',
    isoCode: 'MN',
  },
  {
    title: '네팔',
    description: 'Nepal (Asia)',
    imageUrl: 'https://flagcdn.com/np.svg',
    isoCode: 'NP',
  },
  {
    title: '미얀마',
    description: 'Myanmar (Asia)',
    imageUrl: 'https://flagcdn.com/mm.svg',
    isoCode: 'MM',
  },
  {
    title: '미국',
    description: 'United States of America (America)',
    imageUrl: 'https://flagcdn.com/us.svg',
    isoCode: 'US',
  },
  {
    title: '바누아투',
    description: 'Vanuatu (Asia)',
    imageUrl: 'https://flagcdn.com/vu.svg',
    isoCode: 'VU',
  },
  {
    title: '바하마',
    description: 'Bahamas (America)',
    imageUrl: 'https://flagcdn.com/bs.svg',
    isoCode: 'BS',
  },
  {
    title: '방글라데시',
    description: 'Bangladesh (Asia)',
    imageUrl: 'https://flagcdn.com/bd.svg',
    isoCode: 'BD',
  },
  {
    title: '버뮤다',
    description: 'Bermuda (America)',
    imageUrl: 'https://flagcdn.com/bm.svg',
    isoCode: 'BM',
  },
  {
    title: '베냉',
    description: 'Benin (Africa)',
    imageUrl: 'https://flagcdn.com/bj.svg',
    isoCode: 'BJ',
  },
  {
    title: '베네수엘라',
    description: 'Venezuela (America)',
    imageUrl: 'https://flagcdn.com/ve.svg',
    isoCode: 'VE',
  },
  {
    title: '베트남',
    description: 'Vietnam (Asia)',
    imageUrl: 'https://flagcdn.com/vn.svg',
    isoCode: 'VN',
  },
  {
    title: '벨기에',
    description: 'Belgium (Europe)',
    imageUrl: 'https://flagcdn.com/be.svg',
    isoCode: 'BE',
  },
  {
    title: '벨리즈',
    description: 'Belize (America)',
    imageUrl: 'https://flagcdn.com/bz.svg',
    isoCode: 'BZ',
  },
  {
    title: '벨라루스',
    description: 'Belarus (Europe)',
    imageUrl: 'https://flagcdn.com/by.svg',
    isoCode: 'BY',
  },
  {
    title: '브라질',
    description: 'Brazil (America)',
    imageUrl: 'https://flagcdn.com/br.svg',
    isoCode: 'BR',
  },
  {
    title: '브루나이',
    description: 'Brunei (Asia)',
    imageUrl: 'https://flagcdn.com/bn.svg',
    isoCode: 'BN',
  },
  {
    title: '불가리아',
    description: 'Bulgaria (Europe)',
    imageUrl: 'https://flagcdn.com/bg.svg',
    isoCode: 'BG',
  },
  {
    title: '사모아',
    description: 'Samoa (Asia)',
    imageUrl: 'https://flagcdn.com/ws.svg',
    isoCode: 'WS',
  },
  {
    title: '사우디아라비아',
    description: 'Saudi Arabia (Middle East)',
    imageUrl: 'https://flagcdn.com/sa.svg',
    isoCode: 'SA',
  },
  {
    title: '세네갈',
    description: 'Senegal (Africa)',
    imageUrl: 'https://flagcdn.com/sn.svg',
    isoCode: 'SN',
  },
  {
    title: '수단',
    description: 'Sudan (Africa)',
    imageUrl: 'https://flagcdn.com/sd.svg',
    isoCode: 'SD',
  },
  {
    title: '스리랑카',
    description: 'Sri Lanka (Asia)',
    imageUrl: 'https://flagcdn.com/lk.svg',
    isoCode: 'LK',
  },
  {
    title: '스웨덴',
    description: 'Sweden (Europe)',
    imageUrl: 'https://flagcdn.com/se.svg',
    isoCode: 'SE',
  },
  {
    title: '스위스',
    description: 'Switzerland (Europe)',
    imageUrl: 'https://flagcdn.com/ch.svg',
    isoCode: 'CH',
  },
  {
    title: '스페인',
    description: 'Spain (Europe)',
    imageUrl: 'https://flagcdn.com/es.svg',
    isoCode: 'ES',
  },
  {
    title: '시리아',
    description: 'Syria (Middle East)',
    imageUrl: 'https://flagcdn.com/sy.svg',
    isoCode: 'SY',
  },
  {
    title: '시에라리온',
    description: 'Sierra Leone (Africa)',
    imageUrl: 'https://flagcdn.com/sl.svg',
    isoCode: 'SL',
  },
  {
    title: '싱가포르',
    description: 'Singapore (Asia)',
    imageUrl: 'https://flagcdn.com/sg.svg',
    isoCode: 'SG',
  },
  {
    title: '아랍에미리트',
    description: 'United Arab Emirates (Middle East)',
    imageUrl: 'https://flagcdn.com/ae.svg',
    isoCode: 'AE',
  },
  {
    title: '아르헨티나',
    description: 'Argentina (America)',
    imageUrl: 'https://flagcdn.com/ar.svg',
    isoCode: 'AR',
  },
  {
    title: '아이슬란드',
    description: 'Iceland (Europe)',
    imageUrl: 'https://flagcdn.com/is.svg',
    isoCode: 'IS',
  },
  {
    title: '아이티',
    description: 'Haiti (America)',
    imageUrl: 'https://flagcdn.com/ht.svg',
    isoCode: 'HT',
  },
  {
    title: '아일랜드',
    description: 'Ireland (Europe)',
    imageUrl: 'https://flagcdn.com/ie.svg',
    isoCode: 'IE',
  },
  {
    title: '아제르바이잔',
    description: 'Azerbaijan (Europe)',
    imageUrl: 'https://flagcdn.com/az.svg',
    isoCode: 'AZ',
  },
  {
    title: '안도라',
    description: 'Andorra (Europe)',
    imageUrl: 'https://flagcdn.com/ad.svg',
    isoCode: 'AD',
  },
  {
    title: '알바니아',
    description: 'Albania (Europe)',
    imageUrl: 'https://flagcdn.com/al.svg',
    isoCode: 'AL',
  },
  {
    title: '알제리',
    description: 'Algeria (Africa)',
    imageUrl: 'https://flagcdn.com/dz.svg',
    isoCode: 'DZ',
  },
  {
    title: '앙골라',
    description: 'Angola (Africa)',
    imageUrl: 'https://flagcdn.com/ao.svg',
    isoCode: 'AO',
  },
  {
    title: '앤티가바부다',
    description: 'Antigua and Barbuda (America)',
    imageUrl: 'https://flagcdn.com/ag.svg',
    isoCode: 'AG',
  },
  {
    title: '앵귈라',
    description: 'Anguilla (America)',
    imageUrl: 'https://flagcdn.com/ai.svg',
    isoCode: 'AI',
  },
  {
    title: '에리트레아',
    description: 'Eritrea (Africa)',
    imageUrl: 'https://flagcdn.com/er.svg',
    isoCode: 'ER',
  },
  {
    title: '에스와티니',
    description: 'Eswatini (Africa)',
    imageUrl: 'https://flagcdn.com/sz.svg',
    isoCode: 'SZ',
  },
  {
    title: '에스토니아',
    description: 'Estonia (Europe)',
    imageUrl: 'https://flagcdn.com/ee.svg',
    isoCode: 'EE',
  },
  {
    title: '엘살바도르',
    description: 'El Salvador (America)',
    imageUrl: 'https://flagcdn.com/sv.svg',
    isoCode: 'SV',
  },
  {
    title: '영국',
    description: 'United Kingdom (Europe)',
    imageUrl: 'https://flagcdn.com/gb.svg',
    isoCode: 'GB',
  },
  {
    title: '영국령 버진 아일랜드',
    description: 'British Virgin Islands (America)',
    imageUrl: 'https://flagcdn.com/vg.svg',
    isoCode: 'VG',
  },
  {
    title: '영국령 인도양 제도',
    description: 'British Indian Ocean Territory (Asia)',
    imageUrl: 'https://flagcdn.com/io.svg',
    isoCode: 'IO',
  },
  {
    title: '영국령 남극지역',
    description: 'British Antarctic Territory (Antarctica)',
    imageUrl: 'https://flagcdn.com/aq.svg',
    isoCode: 'AQ',
  },
  {
    title: '예멘',
    description: 'Yemen (Middle East)',
    imageUrl: 'https://flagcdn.com/ye.svg',
    isoCode: 'YE',
  },
  {
    title: '오만',
    description: 'Oman (Middle East)',
    imageUrl: 'https://flagcdn.com/om.svg',
    isoCode: 'OM',
  },
  {
    title: '오스트리아',
    description: 'Austria (Europe)',
    imageUrl: 'https://flagcdn.com/at.svg',
    isoCode: 'AT',
  },
  {
    title: '온두라스',
    description: 'Honduras (America)',
    imageUrl: 'https://flagcdn.com/hn.svg',
    isoCode: 'HN',
  },
  {
    title: '왈리스·퓌튀나',
    description: 'Wallis and Futuna (Asia)',
    imageUrl: 'https://flagcdn.com/wf.svg',
    isoCode: 'WF',
  },
  {
    title: '요르단',
    description: 'Jordan (Middle East)',
    imageUrl: 'https://flagcdn.com/jo.svg',
    isoCode: 'JO',
  },
  {
    title: '우간다',
    description: 'Uganda (Africa)',
    imageUrl: 'https://flagcdn.com/ug.svg',
    isoCode: 'UG',
  },
  {
    title: '우루과이',
    description: 'Uruguay (America)',
    imageUrl: 'https://flagcdn.com/uy.svg',
    isoCode: 'UY',
  },
  {
    title: '우즈베키스탄',
    description: 'Uzbekistan (Europe)',
    imageUrl: 'https://flagcdn.com/uz.svg',
    isoCode: 'UZ',
  },
  {
    title: '우크라이나',
    description: 'Ukraine (Europe)',
    imageUrl: 'https://flagcdn.com/ua.svg',
    isoCode: 'UA',
  },
  {
    title: '이라크',
    description: 'Iraq (Middle East)',
    imageUrl: 'https://flagcdn.com/iq.svg',
    isoCode: 'IQ',
  },
  {
    title: '이란',
    description: 'Iran (Middle East)',
    imageUrl: 'https://flagcdn.com/ir.svg',
    isoCode: 'IR',
  },
  {
    title: '이스라엘',
    description: 'Israel (Middle East)',
    imageUrl: 'https://flagcdn.com/il.svg',
    isoCode: 'IL',
  },
  {
    title: '이집트',
    description: 'Egypt (Africa)',
    imageUrl: 'https://flagcdn.com/eg.svg',
    isoCode: 'EG',
  },
  {
    title: '이탈리아',
    description: 'Italy (Europe)',
    imageUrl: 'https://flagcdn.com/it.svg',
    isoCode: 'IT',
  },
  {
    title: '인도',
    description: 'India (Asia)',
    imageUrl: 'https://flagcdn.com/in.svg',
    isoCode: 'IN',
  },
  {
    title: '인도네시아',
    description: 'Indonesia (Asia)',
    imageUrl: 'https://flagcdn.com/id.svg',
    isoCode: 'ID',
  },
  {
    title: '일본',
    description: 'Japan (Asia)',
    imageUrl: 'https://flagcdn.com/jp.svg',
    isoCode: 'JP',
  },
  {
    title: '자메이카',
    description: 'Jamaica (America)',
    imageUrl: 'https://flagcdn.com/jm.svg',
    isoCode: 'JM',
  },
  {
    title: '잠비아',
    description: 'Zambia (Africa)',
    imageUrl: 'https://flagcdn.com/zm.svg',
    isoCode: 'ZM',
  },
  {
    title: '저지',
    description: 'Jersey (Europe)',
    imageUrl: 'https://flagcdn.com/je.svg',
    isoCode: 'JE',
  },
  {
    title: '중국',
    description: 'China (Asia)',
    imageUrl: 'https://flagcdn.com/cn.svg',
    isoCode: 'CN',
  },
  {
    title: '중앙아프리카',
    description: 'Central African Republic (Africa)',
    imageUrl: 'https://flagcdn.com/cf.svg',
    isoCode: 'CF',
  },
  {
    title: '차드',
    description: 'Chad (Africa)',
    imageUrl: 'https://flagcdn.com/td.svg',
    isoCode: 'TD',
  },
  {
    title: '체코',
    description: 'Czech (Europe)',
    imageUrl: 'https://flagcdn.com/cz.svg',
    isoCode: 'CZ',
  },
  {
    title: '칠레',
    description: 'Chile (America)',
    imageUrl: 'https://flagcdn.com/cl.svg',
    isoCode: 'CL',
  },
  {
    title: '카메룬',
    description: 'Cameroon (Africa)',
    imageUrl: 'https://flagcdn.com/cm.svg',
    isoCode: 'CM',
  },
  {
    title: '카보베르데',
    description: 'Cape Verde (Africa)',
    imageUrl: 'https://flagcdn.com/cv.svg',
    isoCode: 'CV',
  },
  {
    title: '카자흐스탄',
    description: 'Kazakhstan (Europe)',
    imageUrl: 'https://flagcdn.com/kz.svg',
    isoCode: 'KZ',
  },
  {
    title: '카타르',
    description: 'Qatar (Middle East)',
    imageUrl: 'https://flagcdn.com/qa.svg',
    isoCode: 'QA',
  },
  {
    title: '캄보디아',
    description: 'Cambodia (Asia)',
    imageUrl: 'https://flagcdn.com/kh.svg',
    isoCode: 'KH',
  },
  {
    title: '캐나다',
    description: 'Canada (America)',
    imageUrl: 'https://flagcdn.com/ca.svg',
    isoCode: 'CA',
  },
  {
    title: '케냐',
    description: 'Kenya (Africa)',
    imageUrl: 'https://flagcdn.com/ke.svg',
    isoCode: 'KE',
  },
  {
    title: '케이맨제도',
    description: 'Cayman Islands (America)',
    imageUrl: 'https://flagcdn.com/ky.svg',
    isoCode: 'KY',
  },
  {
    title: '코모로',
    description: 'Comoros (Africa)',
    imageUrl: 'https://flagcdn.com/km.svg',
    isoCode: 'KM',
  },
  {
    title: '콜롬비아',
    description: 'Colombia (America)',
    imageUrl: 'https://flagcdn.com/co.svg',
    isoCode: 'CO',
  },
  {
    title: '코트디부아르',
    description: "Côte D'Ivoire (Africa)",
    imageUrl: 'https://flagcdn.com/ci.svg',
    isoCode: 'CI',
  },
  {
    title: '코스타리카',
    description: 'Costa Rica (America)',
    imageUrl: 'https://flagcdn.com/cr.svg',
    isoCode: 'CR',
  },
  {
    title: '코코스제도',
    description: 'Cocos (Keeling) Islands (Asia)',
    imageUrl: 'https://flagcdn.com/cc.svg',
    isoCode: 'CC',
  },
  {
    title: '콩고',
    description: 'Congo (Africa)',
    imageUrl: 'https://flagcdn.com/cg.svg',
    isoCode: 'CG',
  },
  {
    title: '콩고민주공화국',
    description: 'Democratic Republic of Congo (Africa)',
    imageUrl: 'https://flagcdn.com/cd.svg',
    isoCode: 'CD',
  },
  {
    title: '쿠바',
    description: 'Cuba (America)',
    imageUrl: 'https://flagcdn.com/cu.svg',
    isoCode: 'CU',
  },
  {
    title: '쿠웨이트',
    description: 'Kuwait (Middle East)',
    imageUrl: 'https://flagcdn.com/kw.svg',
    isoCode: 'KW',
  },
  {
    title: '크로아티아',
    description: 'Croatia (Europe)',
    imageUrl: 'https://flagcdn.com/hr.svg',
    isoCode: 'HR',
  },
  {
    title: '키르기스탄',
    description: 'Kyrgyz Republic (Europe)',
    imageUrl: 'https://flagcdn.com/kg.svg',
    isoCode: 'KG',
  },
  {
    title: '키리바시',
    description: 'Kiribati (Asia)',
    imageUrl: 'https://flagcdn.com/ki.svg',
    isoCode: 'KI',
  },
  {
    title: '타지키스탄',
    description: 'Tajikistan (Europe)',
    imageUrl: 'https://flagcdn.com/tj.svg',
    isoCode: 'TJ',
  },
  {
    title: '탄자니아',
    description: 'Tanzania (Africa)',
    imageUrl: 'https://flagcdn.com/tz.svg',
    isoCode: 'TZ',
  },
  {
    title: '태국',
    description: 'Thailand (Asia)',
    imageUrl: 'https://flagcdn.com/th.svg',
    isoCode: 'TH',
  },
  {
    title: '터크스·케이커스 제도',
    description: 'Turks and Caicos Islands (America)',
    imageUrl: 'https://flagcdn.com/tc.svg',
    isoCode: 'TC',
  },
  {
    title: '토고',
    description: 'Togo (Africa)',
    imageUrl: 'https://flagcdn.com/tg.svg',
    isoCode: 'TG',
  },
  {
    title: '통가',
    description: 'Tonga (Asia)',
    imageUrl: 'https://flagcdn.com/to.svg',
    isoCode: 'TO',
  },
  {
    title: '투르크메니스탄',
    description: 'Turkmenistan (Europe)',
    imageUrl: 'https://flagcdn.com/tm.svg',
    isoCode: 'TM',
  },
  {
    title: '투발루',
    description: 'Tuvalu (Asia)',
    imageUrl: 'https://flagcdn.com/tv.svg',
    isoCode: 'TV',
  },
  {
    title: '튀니지',
    description: 'Tunisia (Middle East)',
    imageUrl: 'https://flagcdn.com/tn.svg',
    isoCode: 'TN',
  },
  {
    title: '튀르키예',
    description: 'Republic of Turkiye (Europe)',
    imageUrl: 'https://flagcdn.com/tr.svg',
    isoCode: 'TR',
  },
  {
    title: '트리니다드토바고',
    description: 'Trinidad & Tobago (America)',
    imageUrl: 'https://flagcdn.com/tt.svg',
    isoCode: 'TT',
  },
  {
    title: '파나마',
    description: 'Panama (America)',
    imageUrl: 'https://flagcdn.com/pa.svg',
    isoCode: 'PA',
  },
  {
    title: '파라과이',
    description: 'Paraguay (America)',
    imageUrl: 'https://flagcdn.com/py.svg',
    isoCode: 'PY',
  },
  {
    title: '파키스탄',
    description: 'Pakistan (Asia)',
    imageUrl: 'https://flagcdn.com/pk.svg',
    isoCode: 'PK',
  },
  {
    title: '파푸아뉴기니',
    description: 'Papua New Guinea (Asia)',
    imageUrl: 'https://flagcdn.com/pg.svg',
    isoCode: 'PG',
  },
  {
    title: '팔라우',
    description: 'Palau (Asia)',
    imageUrl: 'https://flagcdn.com/pw.svg',
    isoCode: 'PW',
  },
  {
    title: '팔레스타인',
    description: 'Palestine (Middle East)',
    imageUrl: 'https://flagcdn.com/ps.svg',
    isoCode: 'PS',
  },
  {
    title: '페루',
    description: 'Peru (America)',
    imageUrl: 'https://flagcdn.com/pe.svg',
    isoCode: 'PE',
  },
  {
    title: '포르투갈',
    description: 'Portugal (Europe)',
    imageUrl: 'https://flagcdn.com/pt.svg',
    isoCode: 'PT',
  },
  {
    title: '폴란드',
    description: 'Poland (Europe)',
    imageUrl: 'https://flagcdn.com/pl.svg',
    isoCode: 'PL',
  },
  {
    title: '푸에르토리코',
    description: 'Puerto Rico (America)',
    imageUrl: 'https://flagcdn.com/pr.svg',
    isoCode: 'PR',
  },
  {
    title: '프랑스',
    description: 'France (Europe)',
    imageUrl: 'https://flagcdn.com/fr.svg',
    isoCode: 'FR',
  },
  {
    title: '프랑스령 기아나',
    description: 'French Guiana (America)',
    imageUrl: 'https://flagcdn.com/gf.svg',
    isoCode: 'GF',
  },
  {
    title: '프랑스령 폴리네시아',
    description: 'French Polynesia (America)',
    imageUrl: 'https://flagcdn.com/pf.svg',
    isoCode: 'PF',
  },
  {
    title: '피지',
    description: 'Fiji (Asia)',
    imageUrl: 'https://flagcdn.com/fj.svg',
    isoCode: 'FJ',
  },
  {
    title: '핀란드',
    description: 'Finland (Europe)',
    imageUrl: 'https://flagcdn.com/fi.svg',
    isoCode: 'FI',
  },
  {
    title: '필리핀',
    description: 'Philippines (Asia)',
    imageUrl: 'https://flagcdn.com/ph.svg',
    isoCode: 'PH',
  },
  {
    title: '헝가리',
    description: 'Hungary (Europe)',
    imageUrl: 'https://flagcdn.com/hu.svg',
    isoCode: 'HU',
  },
  {
    title: '호주',
    description: 'Australia (Asia)',
    imageUrl: 'https://flagcdn.com/au.svg',
    isoCode: 'AU',
  },
  {
    title: '홍콩',
    description: 'Hong Kong (Asia)',
    imageUrl: 'https://flagcdn.com/hk.svg',
    isoCode: 'HK',
  },
];

export default COUNTRIES;
